import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'
import {Badge,BREAKS,Field,day,hm,money} from './common-v2'

const empty={full_name:'',login:'',job_title:'',shift_start:'08:00',shift_end:'17:00',break_group:'general',rate_8h:0,employment_start_date:'',official_employment:false,official_start_date:''}
const md=v=>v?String(v).slice(5,10):''
const years=(v)=>{if(!v)return 0;const a=new Date(`${v}T00:00:00`),b=new Date();let y=b.getFullYear()-a.getFullYear();if(`${String(b.getMonth()+1).padStart(2,'0')}-${String(b.getDate()).padStart(2,'0')}`<`${String(a.getMonth()+1).padStart(2,'0')}-${String(a.getDate()).padStart(2,'0')}`)y--;return Math.max(0,y)}

export function HRPanel({profile,onClose}){
  const [workers,setWorkers]=useState([]),[edit,setEdit]=useState(null),[form,setForm]=useState(empty),[showArchived,setShowArchived]=useState(false),[msg,setMsg]=useState('')
  async function load(){const {data,error}=await supabase.from('profiles').select('*').eq('role','worker').order('full_name');if(error)setMsg(error.message);else{setWorkers(data||[]);setMsg('')}}
  useEffect(()=>{load()},[])
  const today=day(),todayMD=today.slice(5,10)
  const anniversaries=useMemo(()=>workers.filter(w=>w.active&&((w.employment_start_date&&md(w.employment_start_date)===todayMD)||(w.official_employment&&w.official_start_date&&md(w.official_start_date)===todayMD))),[workers,todayMD])
  const list=workers.filter(w=>showArchived?!w.active:w.active)
  function openEdit(w){setEdit(w);setForm({full_name:w.full_name||'',login:w.login||'',job_title:w.job_title||w.position||'',shift_start:hm(w.shift_start)||'08:00',shift_end:hm(w.shift_end)||'17:00',break_group:w.break_group||'general',rate_8h:Number(w.rate_8h||0),employment_start_date:w.employment_start_date||'',official_employment:Boolean(w.official_employment),official_start_date:w.official_start_date||''})}
  async function save(e){e.preventDefault();const patch={full_name:form.full_name.trim(),job_title:form.job_title.trim(),position:form.job_title.trim(),shift_start:form.shift_start,shift_end:form.shift_end,break_group:form.break_group,rate_8h:Number(form.rate_8h||0),base_rate_8h:Number(form.rate_8h||0),employment_start_date:form.employment_start_date||null,official_employment:Boolean(form.official_employment),official_start_date:form.official_employment?(form.official_start_date||null):null};const {error}=await supabase.from('profiles').update(patch).eq('id',edit.id);if(error)return alert(error.message);setEdit(null);load()}
  async function archive(w){const {data:busy}=await supabase.from('tasks').select('id,title').eq('assigned_to',w.id).in('status',['active','stop_requested']).limit(1);if(busy?.length)return alert(`Нельзя удалить рабочего: у него активно задание «${busy[0].title}». Сначала закройте задание.`);const reason=prompt(`Причина удаления доступа для ${w.full_name}:`,'Уволен / больше не работает');if(reason===null)return;const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('profiles').update({active:false,deactivated_at:new Date().toISOString(),deactivated_by:user?.id||null,deactivation_reason:reason||null}).eq('id',w.id);if(error)return alert(error.message);await supabase.from('tasks').update({status:'cancelled'}).eq('assigned_to',w.id).eq('status','queued');load()}
  async function restore(w){if(!confirm(`Вернуть доступ рабочему ${w.full_name}?`))return;const {error}=await supabase.from('profiles').update({active:true,deactivated_at:null,deactivated_by:null,deactivation_reason:null}).eq('id',w.id);if(error)alert(error.message);else load()}
  return <div className="modal"><div className="modal-card wide"><div className="row between"><div><h2>Кадры</h2><div className="muted">Данные рабочего сохраняются навсегда. «Удалить» означает закрыть доступ и убрать из действующего состава.</div></div><button className="ghost" onClick={onClose}>Закрыть</button></div>
    {msg&&<div className="warning">{msg}</div>}
    {anniversaries.length>0&&<div className="panel"><h3>🎉 Сегодня годовщина</h3>{anniversaries.map(w=><div key={w.id}><b>{w.full_name}</b>{w.employment_start_date&&md(w.employment_start_date)===todayMD&&<> · {years(w.employment_start_date)} г. с начала работы</>}{w.official_employment&&w.official_start_date&&md(w.official_start_date)===todayMD&&<> · {years(w.official_start_date)} г. с официального трудоустройства</>}</div>)}</div>}
    <div className="row"><button className={!showArchived?'':'secondary'} onClick={()=>setShowArchived(false)}>Действующие</button><button className={showArchived?'':'secondary'} onClick={()=>setShowArchived(true)}>Удалённые / архив</button></div>
    <div className="table"><table><thead><tr><th>Рабочий</th><th>Должность</th><th>Начало работы</th><th>Оформление</th><th>Ставка / 8ч</th><th></th></tr></thead><tbody>{list.map(w=><tr key={w.id}><td><b>{w.full_name}</b><div className="muted">{w.login}</div></td><td>{w.job_title||'—'}</td><td>{w.employment_start_date||'—'}</td><td>{w.official_employment?`Официально${w.official_start_date?` с ${w.official_start_date}`:''}`:'Неофициально'}</td><td>{money(w.rate_8h)}</td><td>{w.active?<div className="row"><button className="secondary" onClick={()=>openEdit(w)}>Настройки</button><button className="danger" onClick={()=>archive(w)}>Удалить рабочего</button></div>:<button className="secondary" onClick={()=>restore(w)}>Восстановить</button>}</td></tr>)}</tbody></table></div>
    {edit&&<div className="panel"><div className="row between"><h3>Настройки: {edit.full_name}</h3><button className="ghost" onClick={()=>setEdit(null)}>Закрыть</button></div><form className="form" onSubmit={save}><Field label="ФИО"><input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></Field><Field label="Должность"><input value={form.job_title} onChange={e=>setForm({...form,job_title:e.target.value})}/></Field><Field label="Начало смены"><input type="time" value={form.shift_start} onChange={e=>setForm({...form,shift_start:e.target.value})}/></Field><Field label="Конец смены"><input type="time" value={form.shift_end} onChange={e=>setForm({...form,shift_end:e.target.value})}/></Field><Field label="Перерывы"><select value={form.break_group} onChange={e=>setForm({...form,break_group:e.target.value})}>{BREAKS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></Field><Field label="Ставка / 8ч"><input type="number" min="0" value={form.rate_8h} onChange={e=>setForm({...form,rate_8h:e.target.value})}/></Field><Field label="Дата начала работы"><input type="date" value={form.employment_start_date} onChange={e=>setForm({...form,employment_start_date:e.target.value})}/></Field><Field label="Официально трудоустроен"><select value={form.official_employment?'yes':'no'} onChange={e=>setForm({...form,official_employment:e.target.value==='yes'})}><option value="no">Нет</option><option value="yes">Да</option></select></Field>{form.official_employment&&<Field label="Дата официального трудоустройства"><input type="date" value={form.official_start_date} onChange={e=>setForm({...form,official_start_date:e.target.value})}/></Field>}<button className="wide">Сохранить кадровые данные</button></form></div>}
  </div></div>
}